
## Build
FROM golang:latest AS build

WORKDIR /

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /swiftui-golang-app-demo

## Deploy
FROM gcr.io/distroless/base-debian11

WORKDIR /

COPY --from=build /swiftui-golang-app-demo /swiftui-golang-app-demo

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/swiftui-golang-app-demo"]


