// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/competition"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/competitionresult"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/predicate"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/profile"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/squad"
)

// CompetitionResultQuery is the builder for querying CompetitionResult entities.
type CompetitionResultQuery struct {
	config
	ctx             *QueryContext
	order           []competitionresult.OrderOption
	inters          []Interceptor
	predicates      []predicate.CompetitionResult
	withCompetition *CompetitionQuery
	withProfile     *ProfileQuery
	withSquad       *SquadQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CompetitionResultQuery builder.
func (crq *CompetitionResultQuery) Where(ps ...predicate.CompetitionResult) *CompetitionResultQuery {
	crq.predicates = append(crq.predicates, ps...)
	return crq
}

// Limit the number of records to be returned by this query.
func (crq *CompetitionResultQuery) Limit(limit int) *CompetitionResultQuery {
	crq.ctx.Limit = &limit
	return crq
}

// Offset to start from.
func (crq *CompetitionResultQuery) Offset(offset int) *CompetitionResultQuery {
	crq.ctx.Offset = &offset
	return crq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (crq *CompetitionResultQuery) Unique(unique bool) *CompetitionResultQuery {
	crq.ctx.Unique = &unique
	return crq
}

// Order specifies how the records should be ordered.
func (crq *CompetitionResultQuery) Order(o ...competitionresult.OrderOption) *CompetitionResultQuery {
	crq.order = append(crq.order, o...)
	return crq
}

// QueryCompetition chains the current query on the "competition" edge.
func (crq *CompetitionResultQuery) QueryCompetition() *CompetitionQuery {
	query := (&CompetitionClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competitionresult.Table, competitionresult.FieldID, selector),
			sqlgraph.To(competition.Table, competition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, competitionresult.CompetitionTable, competitionresult.CompetitionColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProfile chains the current query on the "profile" edge.
func (crq *CompetitionResultQuery) QueryProfile() *ProfileQuery {
	query := (&ProfileClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competitionresult.Table, competitionresult.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, competitionresult.ProfileTable, competitionresult.ProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySquad chains the current query on the "squad" edge.
func (crq *CompetitionResultQuery) QuerySquad() *SquadQuery {
	query := (&SquadClient{config: crq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := crq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := crq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competitionresult.Table, competitionresult.FieldID, selector),
			sqlgraph.To(squad.Table, squad.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, competitionresult.SquadTable, competitionresult.SquadColumn),
		)
		fromU = sqlgraph.SetNeighbors(crq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CompetitionResult entity from the query.
// Returns a *NotFoundError when no CompetitionResult was found.
func (crq *CompetitionResultQuery) First(ctx context.Context) (*CompetitionResult, error) {
	nodes, err := crq.Limit(1).All(setContextOp(ctx, crq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{competitionresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (crq *CompetitionResultQuery) FirstX(ctx context.Context) *CompetitionResult {
	node, err := crq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CompetitionResult ID from the query.
// Returns a *NotFoundError when no CompetitionResult ID was found.
func (crq *CompetitionResultQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = crq.Limit(1).IDs(setContextOp(ctx, crq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{competitionresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (crq *CompetitionResultQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := crq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CompetitionResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CompetitionResult entity is found.
// Returns a *NotFoundError when no CompetitionResult entities are found.
func (crq *CompetitionResultQuery) Only(ctx context.Context) (*CompetitionResult, error) {
	nodes, err := crq.Limit(2).All(setContextOp(ctx, crq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{competitionresult.Label}
	default:
		return nil, &NotSingularError{competitionresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (crq *CompetitionResultQuery) OnlyX(ctx context.Context) *CompetitionResult {
	node, err := crq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CompetitionResult ID in the query.
// Returns a *NotSingularError when more than one CompetitionResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (crq *CompetitionResultQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = crq.Limit(2).IDs(setContextOp(ctx, crq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{competitionresult.Label}
	default:
		err = &NotSingularError{competitionresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (crq *CompetitionResultQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := crq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CompetitionResults.
func (crq *CompetitionResultQuery) All(ctx context.Context) ([]*CompetitionResult, error) {
	ctx = setContextOp(ctx, crq.ctx, "All")
	if err := crq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CompetitionResult, *CompetitionResultQuery]()
	return withInterceptors[[]*CompetitionResult](ctx, crq, qr, crq.inters)
}

// AllX is like All, but panics if an error occurs.
func (crq *CompetitionResultQuery) AllX(ctx context.Context) []*CompetitionResult {
	nodes, err := crq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CompetitionResult IDs.
func (crq *CompetitionResultQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if crq.ctx.Unique == nil && crq.path != nil {
		crq.Unique(true)
	}
	ctx = setContextOp(ctx, crq.ctx, "IDs")
	if err = crq.Select(competitionresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (crq *CompetitionResultQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := crq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (crq *CompetitionResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, crq.ctx, "Count")
	if err := crq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, crq, querierCount[*CompetitionResultQuery](), crq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (crq *CompetitionResultQuery) CountX(ctx context.Context) int {
	count, err := crq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (crq *CompetitionResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, crq.ctx, "Exist")
	switch _, err := crq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (crq *CompetitionResultQuery) ExistX(ctx context.Context) bool {
	exist, err := crq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CompetitionResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (crq *CompetitionResultQuery) Clone() *CompetitionResultQuery {
	if crq == nil {
		return nil
	}
	return &CompetitionResultQuery{
		config:          crq.config,
		ctx:             crq.ctx.Clone(),
		order:           append([]competitionresult.OrderOption{}, crq.order...),
		inters:          append([]Interceptor{}, crq.inters...),
		predicates:      append([]predicate.CompetitionResult{}, crq.predicates...),
		withCompetition: crq.withCompetition.Clone(),
		withProfile:     crq.withProfile.Clone(),
		withSquad:       crq.withSquad.Clone(),
		// clone intermediate query.
		sql:  crq.sql.Clone(),
		path: crq.path,
	}
}

// WithCompetition tells the query-builder to eager-load the nodes that are connected to
// the "competition" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CompetitionResultQuery) WithCompetition(opts ...func(*CompetitionQuery)) *CompetitionResultQuery {
	query := (&CompetitionClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withCompetition = query
	return crq
}

// WithProfile tells the query-builder to eager-load the nodes that are connected to
// the "profile" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CompetitionResultQuery) WithProfile(opts ...func(*ProfileQuery)) *CompetitionResultQuery {
	query := (&ProfileClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withProfile = query
	return crq
}

// WithSquad tells the query-builder to eager-load the nodes that are connected to
// the "squad" edge. The optional arguments are used to configure the query builder of the edge.
func (crq *CompetitionResultQuery) WithSquad(opts ...func(*SquadQuery)) *CompetitionResultQuery {
	query := (&SquadClient{config: crq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	crq.withSquad = query
	return crq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CompetitionResult.Query().
//		GroupBy(competitionresult.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (crq *CompetitionResultQuery) GroupBy(field string, fields ...string) *CompetitionResultGroupBy {
	crq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CompetitionResultGroupBy{build: crq}
	grbuild.flds = &crq.ctx.Fields
	grbuild.label = competitionresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.CompetitionResult.Query().
//		Select(competitionresult.FieldCreatedAt).
//		Scan(ctx, &v)
func (crq *CompetitionResultQuery) Select(fields ...string) *CompetitionResultSelect {
	crq.ctx.Fields = append(crq.ctx.Fields, fields...)
	sbuild := &CompetitionResultSelect{CompetitionResultQuery: crq}
	sbuild.label = competitionresult.Label
	sbuild.flds, sbuild.scan = &crq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CompetitionResultSelect configured with the given aggregations.
func (crq *CompetitionResultQuery) Aggregate(fns ...AggregateFunc) *CompetitionResultSelect {
	return crq.Select().Aggregate(fns...)
}

func (crq *CompetitionResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range crq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, crq); err != nil {
				return err
			}
		}
	}
	for _, f := range crq.ctx.Fields {
		if !competitionresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if crq.path != nil {
		prev, err := crq.path(ctx)
		if err != nil {
			return err
		}
		crq.sql = prev
	}
	return nil
}

func (crq *CompetitionResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CompetitionResult, error) {
	var (
		nodes       = []*CompetitionResult{}
		withFKs     = crq.withFKs
		_spec       = crq.querySpec()
		loadedTypes = [3]bool{
			crq.withCompetition != nil,
			crq.withProfile != nil,
			crq.withSquad != nil,
		}
	)
	if crq.withCompetition != nil || crq.withProfile != nil || crq.withSquad != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, competitionresult.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CompetitionResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CompetitionResult{config: crq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(crq.modifiers) > 0 {
		_spec.Modifiers = crq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, crq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := crq.withCompetition; query != nil {
		if err := crq.loadCompetition(ctx, query, nodes, nil,
			func(n *CompetitionResult, e *Competition) { n.Edges.Competition = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withProfile; query != nil {
		if err := crq.loadProfile(ctx, query, nodes, nil,
			func(n *CompetitionResult, e *Profile) { n.Edges.Profile = e }); err != nil {
			return nil, err
		}
	}
	if query := crq.withSquad; query != nil {
		if err := crq.loadSquad(ctx, query, nodes, nil,
			func(n *CompetitionResult, e *Squad) { n.Edges.Squad = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (crq *CompetitionResultQuery) loadCompetition(ctx context.Context, query *CompetitionQuery, nodes []*CompetitionResult, init func(*CompetitionResult), assign func(*CompetitionResult, *Competition)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CompetitionResult)
	for i := range nodes {
		if nodes[i].competition_result_competition == nil {
			continue
		}
		fk := *nodes[i].competition_result_competition
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(competition.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "competition_result_competition" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CompetitionResultQuery) loadProfile(ctx context.Context, query *ProfileQuery, nodes []*CompetitionResult, init func(*CompetitionResult), assign func(*CompetitionResult, *Profile)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CompetitionResult)
	for i := range nodes {
		if nodes[i].competition_result_profile == nil {
			continue
		}
		fk := *nodes[i].competition_result_profile
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(profile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "competition_result_profile" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (crq *CompetitionResultQuery) loadSquad(ctx context.Context, query *SquadQuery, nodes []*CompetitionResult, init func(*CompetitionResult), assign func(*CompetitionResult, *Squad)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*CompetitionResult)
	for i := range nodes {
		if nodes[i].competition_result_squad == nil {
			continue
		}
		fk := *nodes[i].competition_result_squad
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(squad.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "competition_result_squad" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (crq *CompetitionResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := crq.querySpec()
	if len(crq.modifiers) > 0 {
		_spec.Modifiers = crq.modifiers
	}
	_spec.Node.Columns = crq.ctx.Fields
	if len(crq.ctx.Fields) > 0 {
		_spec.Unique = crq.ctx.Unique != nil && *crq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, crq.driver, _spec)
}

func (crq *CompetitionResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(competitionresult.Table, competitionresult.Columns, sqlgraph.NewFieldSpec(competitionresult.FieldID, field.TypeUUID))
	_spec.From = crq.sql
	if unique := crq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if crq.path != nil {
		_spec.Unique = true
	}
	if fields := crq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, competitionresult.FieldID)
		for i := range fields {
			if fields[i] != competitionresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := crq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := crq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := crq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := crq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (crq *CompetitionResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(crq.driver.Dialect())
	t1 := builder.Table(competitionresult.Table)
	columns := crq.ctx.Fields
	if len(columns) == 0 {
		columns = competitionresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if crq.sql != nil {
		selector = crq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if crq.ctx.Unique != nil && *crq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range crq.modifiers {
		m(selector)
	}
	for _, p := range crq.predicates {
		p(selector)
	}
	for _, p := range crq.order {
		p(selector)
	}
	if offset := crq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := crq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (crq *CompetitionResultQuery) Modify(modifiers ...func(s *sql.Selector)) *CompetitionResultSelect {
	crq.modifiers = append(crq.modifiers, modifiers...)
	return crq.Select()
}

// CompetitionResultGroupBy is the group-by builder for CompetitionResult entities.
type CompetitionResultGroupBy struct {
	selector
	build *CompetitionResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (crgb *CompetitionResultGroupBy) Aggregate(fns ...AggregateFunc) *CompetitionResultGroupBy {
	crgb.fns = append(crgb.fns, fns...)
	return crgb
}

// Scan applies the selector query and scans the result into the given value.
func (crgb *CompetitionResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crgb.build.ctx, "GroupBy")
	if err := crgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompetitionResultQuery, *CompetitionResultGroupBy](ctx, crgb.build, crgb, crgb.build.inters, v)
}

func (crgb *CompetitionResultGroupBy) sqlScan(ctx context.Context, root *CompetitionResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(crgb.fns))
	for _, fn := range crgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*crgb.flds)+len(crgb.fns))
		for _, f := range *crgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*crgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CompetitionResultSelect is the builder for selecting fields of CompetitionResult entities.
type CompetitionResultSelect struct {
	*CompetitionResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (crs *CompetitionResultSelect) Aggregate(fns ...AggregateFunc) *CompetitionResultSelect {
	crs.fns = append(crs.fns, fns...)
	return crs
}

// Scan applies the selector query and scans the result into the given value.
func (crs *CompetitionResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, crs.ctx, "Select")
	if err := crs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompetitionResultQuery, *CompetitionResultSelect](ctx, crs.CompetitionResultQuery, crs, crs.inters, v)
}

func (crs *CompetitionResultSelect) sqlScan(ctx context.Context, root *CompetitionResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(crs.fns))
	for _, fn := range crs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*crs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := crs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (crs *CompetitionResultSelect) Modify(modifiers ...func(s *sql.Selector)) *CompetitionResultSelect {
	crs.modifiers = append(crs.modifiers, modifiers...)
	return crs
}
