// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/competition"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/competitionresult"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/predicate"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/profile"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/workout"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/workoutdata"
)

// CompetitionQuery is the builder for querying Competition entities.
type CompetitionQuery struct {
	config
	ctx              *QueryContext
	order            []competition.OrderOption
	inters           []Interceptor
	predicates       []predicate.Competition
	withOwner        *ProfileQuery
	withParticipants *ProfileQuery
	withWorkouts     *WorkoutQuery
	withWorkoutData  *WorkoutDataQuery
	withResults      *CompetitionResultQuery
	withFKs          bool
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CompetitionQuery builder.
func (cq *CompetitionQuery) Where(ps ...predicate.Competition) *CompetitionQuery {
	cq.predicates = append(cq.predicates, ps...)
	return cq
}

// Limit the number of records to be returned by this query.
func (cq *CompetitionQuery) Limit(limit int) *CompetitionQuery {
	cq.ctx.Limit = &limit
	return cq
}

// Offset to start from.
func (cq *CompetitionQuery) Offset(offset int) *CompetitionQuery {
	cq.ctx.Offset = &offset
	return cq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cq *CompetitionQuery) Unique(unique bool) *CompetitionQuery {
	cq.ctx.Unique = &unique
	return cq
}

// Order specifies how the records should be ordered.
func (cq *CompetitionQuery) Order(o ...competition.OrderOption) *CompetitionQuery {
	cq.order = append(cq.order, o...)
	return cq
}

// QueryOwner chains the current query on the "owner" edge.
func (cq *CompetitionQuery) QueryOwner() *ProfileQuery {
	query := (&ProfileClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competition.Table, competition.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, competition.OwnerTable, competition.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParticipants chains the current query on the "participants" edge.
func (cq *CompetitionQuery) QueryParticipants() *ProfileQuery {
	query := (&ProfileClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competition.Table, competition.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, competition.ParticipantsTable, competition.ParticipantsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkouts chains the current query on the "workouts" edge.
func (cq *CompetitionQuery) QueryWorkouts() *WorkoutQuery {
	query := (&WorkoutClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competition.Table, competition.FieldID, selector),
			sqlgraph.To(workout.Table, workout.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, competition.WorkoutsTable, competition.WorkoutsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkoutData chains the current query on the "workout_data" edge.
func (cq *CompetitionQuery) QueryWorkoutData() *WorkoutDataQuery {
	query := (&WorkoutDataClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competition.Table, competition.FieldID, selector),
			sqlgraph.To(workoutdata.Table, workoutdata.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, competition.WorkoutDataTable, competition.WorkoutDataColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryResults chains the current query on the "results" edge.
func (cq *CompetitionQuery) QueryResults() *CompetitionResultQuery {
	query := (&CompetitionResultClient{config: cq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(competition.Table, competition.FieldID, selector),
			sqlgraph.To(competitionresult.Table, competitionresult.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, competition.ResultsTable, competition.ResultsColumn),
		)
		fromU = sqlgraph.SetNeighbors(cq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Competition entity from the query.
// Returns a *NotFoundError when no Competition was found.
func (cq *CompetitionQuery) First(ctx context.Context) (*Competition, error) {
	nodes, err := cq.Limit(1).All(setContextOp(ctx, cq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{competition.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cq *CompetitionQuery) FirstX(ctx context.Context) *Competition {
	node, err := cq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Competition ID from the query.
// Returns a *NotFoundError when no Competition ID was found.
func (cq *CompetitionQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(1).IDs(setContextOp(ctx, cq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{competition.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cq *CompetitionQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := cq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Competition entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Competition entity is found.
// Returns a *NotFoundError when no Competition entities are found.
func (cq *CompetitionQuery) Only(ctx context.Context) (*Competition, error) {
	nodes, err := cq.Limit(2).All(setContextOp(ctx, cq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{competition.Label}
	default:
		return nil, &NotSingularError{competition.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cq *CompetitionQuery) OnlyX(ctx context.Context) *Competition {
	node, err := cq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Competition ID in the query.
// Returns a *NotSingularError when more than one Competition ID is found.
// Returns a *NotFoundError when no entities are found.
func (cq *CompetitionQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = cq.Limit(2).IDs(setContextOp(ctx, cq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{competition.Label}
	default:
		err = &NotSingularError{competition.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cq *CompetitionQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := cq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Competitions.
func (cq *CompetitionQuery) All(ctx context.Context) ([]*Competition, error) {
	ctx = setContextOp(ctx, cq.ctx, "All")
	if err := cq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Competition, *CompetitionQuery]()
	return withInterceptors[[]*Competition](ctx, cq, qr, cq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cq *CompetitionQuery) AllX(ctx context.Context) []*Competition {
	nodes, err := cq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Competition IDs.
func (cq *CompetitionQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if cq.ctx.Unique == nil && cq.path != nil {
		cq.Unique(true)
	}
	ctx = setContextOp(ctx, cq.ctx, "IDs")
	if err = cq.Select(competition.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cq *CompetitionQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := cq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cq *CompetitionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cq.ctx, "Count")
	if err := cq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cq, querierCount[*CompetitionQuery](), cq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cq *CompetitionQuery) CountX(ctx context.Context) int {
	count, err := cq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cq *CompetitionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cq.ctx, "Exist")
	switch _, err := cq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cq *CompetitionQuery) ExistX(ctx context.Context) bool {
	exist, err := cq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CompetitionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cq *CompetitionQuery) Clone() *CompetitionQuery {
	if cq == nil {
		return nil
	}
	return &CompetitionQuery{
		config:           cq.config,
		ctx:              cq.ctx.Clone(),
		order:            append([]competition.OrderOption{}, cq.order...),
		inters:           append([]Interceptor{}, cq.inters...),
		predicates:       append([]predicate.Competition{}, cq.predicates...),
		withOwner:        cq.withOwner.Clone(),
		withParticipants: cq.withParticipants.Clone(),
		withWorkouts:     cq.withWorkouts.Clone(),
		withWorkoutData:  cq.withWorkoutData.Clone(),
		withResults:      cq.withResults.Clone(),
		// clone intermediate query.
		sql:  cq.sql.Clone(),
		path: cq.path,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CompetitionQuery) WithOwner(opts ...func(*ProfileQuery)) *CompetitionQuery {
	query := (&ProfileClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withOwner = query
	return cq
}

// WithParticipants tells the query-builder to eager-load the nodes that are connected to
// the "participants" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CompetitionQuery) WithParticipants(opts ...func(*ProfileQuery)) *CompetitionQuery {
	query := (&ProfileClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withParticipants = query
	return cq
}

// WithWorkouts tells the query-builder to eager-load the nodes that are connected to
// the "workouts" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CompetitionQuery) WithWorkouts(opts ...func(*WorkoutQuery)) *CompetitionQuery {
	query := (&WorkoutClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withWorkouts = query
	return cq
}

// WithWorkoutData tells the query-builder to eager-load the nodes that are connected to
// the "workout_data" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CompetitionQuery) WithWorkoutData(opts ...func(*WorkoutDataQuery)) *CompetitionQuery {
	query := (&WorkoutDataClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withWorkoutData = query
	return cq
}

// WithResults tells the query-builder to eager-load the nodes that are connected to
// the "results" edge. The optional arguments are used to configure the query builder of the edge.
func (cq *CompetitionQuery) WithResults(opts ...func(*CompetitionResultQuery)) *CompetitionQuery {
	query := (&CompetitionResultClient{config: cq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cq.withResults = query
	return cq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Competition.Query().
//		GroupBy(competition.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cq *CompetitionQuery) GroupBy(field string, fields ...string) *CompetitionGroupBy {
	cq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CompetitionGroupBy{build: cq}
	grbuild.flds = &cq.ctx.Fields
	grbuild.label = competition.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Competition.Query().
//		Select(competition.FieldCreatedAt).
//		Scan(ctx, &v)
func (cq *CompetitionQuery) Select(fields ...string) *CompetitionSelect {
	cq.ctx.Fields = append(cq.ctx.Fields, fields...)
	sbuild := &CompetitionSelect{CompetitionQuery: cq}
	sbuild.label = competition.Label
	sbuild.flds, sbuild.scan = &cq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CompetitionSelect configured with the given aggregations.
func (cq *CompetitionQuery) Aggregate(fns ...AggregateFunc) *CompetitionSelect {
	return cq.Select().Aggregate(fns...)
}

func (cq *CompetitionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cq); err != nil {
				return err
			}
		}
	}
	for _, f := range cq.ctx.Fields {
		if !competition.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cq.path != nil {
		prev, err := cq.path(ctx)
		if err != nil {
			return err
		}
		cq.sql = prev
	}
	return nil
}

func (cq *CompetitionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Competition, error) {
	var (
		nodes       = []*Competition{}
		withFKs     = cq.withFKs
		_spec       = cq.querySpec()
		loadedTypes = [5]bool{
			cq.withOwner != nil,
			cq.withParticipants != nil,
			cq.withWorkouts != nil,
			cq.withWorkoutData != nil,
			cq.withResults != nil,
		}
	)
	if cq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, competition.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Competition).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Competition{config: cq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cq.withOwner; query != nil {
		if err := cq.loadOwner(ctx, query, nodes, nil,
			func(n *Competition, e *Profile) { n.Edges.Owner = e }); err != nil {
			return nil, err
		}
	}
	if query := cq.withParticipants; query != nil {
		if err := cq.loadParticipants(ctx, query, nodes,
			func(n *Competition) { n.Edges.Participants = []*Profile{} },
			func(n *Competition, e *Profile) { n.Edges.Participants = append(n.Edges.Participants, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withWorkouts; query != nil {
		if err := cq.loadWorkouts(ctx, query, nodes,
			func(n *Competition) { n.Edges.Workouts = []*Workout{} },
			func(n *Competition, e *Workout) { n.Edges.Workouts = append(n.Edges.Workouts, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withWorkoutData; query != nil {
		if err := cq.loadWorkoutData(ctx, query, nodes,
			func(n *Competition) { n.Edges.WorkoutData = []*WorkoutData{} },
			func(n *Competition, e *WorkoutData) { n.Edges.WorkoutData = append(n.Edges.WorkoutData, e) }); err != nil {
			return nil, err
		}
	}
	if query := cq.withResults; query != nil {
		if err := cq.loadResults(ctx, query, nodes,
			func(n *Competition) { n.Edges.Results = []*CompetitionResult{} },
			func(n *Competition, e *CompetitionResult) { n.Edges.Results = append(n.Edges.Results, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cq *CompetitionQuery) loadOwner(ctx context.Context, query *ProfileQuery, nodes []*Competition, init func(*Competition), assign func(*Competition, *Profile)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Competition)
	for i := range nodes {
		if nodes[i].competition_owner == nil {
			continue
		}
		fk := *nodes[i].competition_owner
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(profile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "competition_owner" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (cq *CompetitionQuery) loadParticipants(ctx context.Context, query *ProfileQuery, nodes []*Competition, init func(*Competition), assign func(*Competition, *Profile)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uuid.UUID]*Competition)
	nids := make(map[uuid.UUID]map[*Competition]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(competition.ParticipantsTable)
		s.Join(joinT).On(s.C(profile.FieldID), joinT.C(competition.ParticipantsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(competition.ParticipantsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(competition.ParticipantsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(uuid.UUID)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := *values[0].(*uuid.UUID)
				inValue := *values[1].(*uuid.UUID)
				if nids[inValue] == nil {
					nids[inValue] = map[*Competition]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Profile](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "participants" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (cq *CompetitionQuery) loadWorkouts(ctx context.Context, query *WorkoutQuery, nodes []*Competition, init func(*Competition), assign func(*Competition, *Workout)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Competition)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Workout(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(competition.WorkoutsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.workout_competition
		if fk == nil {
			return fmt.Errorf(`foreign-key "workout_competition" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workout_competition" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CompetitionQuery) loadWorkoutData(ctx context.Context, query *WorkoutDataQuery, nodes []*Competition, init func(*Competition), assign func(*Competition, *WorkoutData)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Competition)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.WorkoutData(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(competition.WorkoutDataColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.workout_data_competition
		if fk == nil {
			return fmt.Errorf(`foreign-key "workout_data_competition" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workout_data_competition" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (cq *CompetitionQuery) loadResults(ctx context.Context, query *CompetitionResultQuery, nodes []*Competition, init func(*Competition), assign func(*Competition, *CompetitionResult)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Competition)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.CompetitionResult(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(competition.ResultsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.competition_result_competition
		if fk == nil {
			return fmt.Errorf(`foreign-key "competition_result_competition" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "competition_result_competition" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (cq *CompetitionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cq.querySpec()
	if len(cq.modifiers) > 0 {
		_spec.Modifiers = cq.modifiers
	}
	_spec.Node.Columns = cq.ctx.Fields
	if len(cq.ctx.Fields) > 0 {
		_spec.Unique = cq.ctx.Unique != nil && *cq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cq.driver, _spec)
}

func (cq *CompetitionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(competition.Table, competition.Columns, sqlgraph.NewFieldSpec(competition.FieldID, field.TypeUUID))
	_spec.From = cq.sql
	if unique := cq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cq.path != nil {
		_spec.Unique = true
	}
	if fields := cq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, competition.FieldID)
		for i := range fields {
			if fields[i] != competition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cq *CompetitionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cq.driver.Dialect())
	t1 := builder.Table(competition.Table)
	columns := cq.ctx.Fields
	if len(columns) == 0 {
		columns = competition.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cq.sql != nil {
		selector = cq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cq.ctx.Unique != nil && *cq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range cq.modifiers {
		m(selector)
	}
	for _, p := range cq.predicates {
		p(selector)
	}
	for _, p := range cq.order {
		p(selector)
	}
	if offset := cq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cq *CompetitionQuery) Modify(modifiers ...func(s *sql.Selector)) *CompetitionSelect {
	cq.modifiers = append(cq.modifiers, modifiers...)
	return cq.Select()
}

// CompetitionGroupBy is the group-by builder for Competition entities.
type CompetitionGroupBy struct {
	selector
	build *CompetitionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cgb *CompetitionGroupBy) Aggregate(fns ...AggregateFunc) *CompetitionGroupBy {
	cgb.fns = append(cgb.fns, fns...)
	return cgb
}

// Scan applies the selector query and scans the result into the given value.
func (cgb *CompetitionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cgb.build.ctx, "GroupBy")
	if err := cgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompetitionQuery, *CompetitionGroupBy](ctx, cgb.build, cgb, cgb.build.inters, v)
}

func (cgb *CompetitionGroupBy) sqlScan(ctx context.Context, root *CompetitionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cgb.fns))
	for _, fn := range cgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cgb.flds)+len(cgb.fns))
		for _, f := range *cgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CompetitionSelect is the builder for selecting fields of Competition entities.
type CompetitionSelect struct {
	*CompetitionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cs *CompetitionSelect) Aggregate(fns ...AggregateFunc) *CompetitionSelect {
	cs.fns = append(cs.fns, fns...)
	return cs
}

// Scan applies the selector query and scans the result into the given value.
func (cs *CompetitionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cs.ctx, "Select")
	if err := cs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CompetitionQuery, *CompetitionSelect](ctx, cs.CompetitionQuery, cs, cs.inters, v)
}

func (cs *CompetitionSelect) sqlScan(ctx context.Context, root *CompetitionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cs.fns))
	for _, fn := range cs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cs *CompetitionSelect) Modify(modifiers ...func(s *sql.Selector)) *CompetitionSelect {
	cs.modifiers = append(cs.modifiers, modifiers...)
	return cs
}
