// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/competition"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/goal"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/predicate"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/profile"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/squad"
)

// GoalQuery is the builder for querying Goal entities.
type GoalQuery struct {
	config
	ctx             *QueryContext
	order           []goal.OrderOption
	inters          []Interceptor
	predicates      []predicate.Goal
	withProfile     *ProfileQuery
	withCompetition *CompetitionQuery
	withSquad       *SquadQuery
	withFKs         bool
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GoalQuery builder.
func (gq *GoalQuery) Where(ps ...predicate.Goal) *GoalQuery {
	gq.predicates = append(gq.predicates, ps...)
	return gq
}

// Limit the number of records to be returned by this query.
func (gq *GoalQuery) Limit(limit int) *GoalQuery {
	gq.ctx.Limit = &limit
	return gq
}

// Offset to start from.
func (gq *GoalQuery) Offset(offset int) *GoalQuery {
	gq.ctx.Offset = &offset
	return gq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gq *GoalQuery) Unique(unique bool) *GoalQuery {
	gq.ctx.Unique = &unique
	return gq
}

// Order specifies how the records should be ordered.
func (gq *GoalQuery) Order(o ...goal.OrderOption) *GoalQuery {
	gq.order = append(gq.order, o...)
	return gq
}

// QueryProfile chains the current query on the "profile" edge.
func (gq *GoalQuery) QueryProfile() *ProfileQuery {
	query := (&ProfileClient{config: gq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goal.Table, goal.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, goal.ProfileTable, goal.ProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCompetition chains the current query on the "competition" edge.
func (gq *GoalQuery) QueryCompetition() *CompetitionQuery {
	query := (&CompetitionClient{config: gq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goal.Table, goal.FieldID, selector),
			sqlgraph.To(competition.Table, competition.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, goal.CompetitionTable, goal.CompetitionColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySquad chains the current query on the "squad" edge.
func (gq *GoalQuery) QuerySquad() *SquadQuery {
	query := (&SquadClient{config: gq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(goal.Table, goal.FieldID, selector),
			sqlgraph.To(squad.Table, squad.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, goal.SquadTable, goal.SquadColumn),
		)
		fromU = sqlgraph.SetNeighbors(gq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Goal entity from the query.
// Returns a *NotFoundError when no Goal was found.
func (gq *GoalQuery) First(ctx context.Context) (*Goal, error) {
	nodes, err := gq.Limit(1).All(setContextOp(ctx, gq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{goal.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gq *GoalQuery) FirstX(ctx context.Context) *Goal {
	node, err := gq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Goal ID from the query.
// Returns a *NotFoundError when no Goal ID was found.
func (gq *GoalQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = gq.Limit(1).IDs(setContextOp(ctx, gq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{goal.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gq *GoalQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := gq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Goal entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Goal entity is found.
// Returns a *NotFoundError when no Goal entities are found.
func (gq *GoalQuery) Only(ctx context.Context) (*Goal, error) {
	nodes, err := gq.Limit(2).All(setContextOp(ctx, gq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{goal.Label}
	default:
		return nil, &NotSingularError{goal.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gq *GoalQuery) OnlyX(ctx context.Context) *Goal {
	node, err := gq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Goal ID in the query.
// Returns a *NotSingularError when more than one Goal ID is found.
// Returns a *NotFoundError when no entities are found.
func (gq *GoalQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = gq.Limit(2).IDs(setContextOp(ctx, gq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{goal.Label}
	default:
		err = &NotSingularError{goal.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gq *GoalQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := gq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Goals.
func (gq *GoalQuery) All(ctx context.Context) ([]*Goal, error) {
	ctx = setContextOp(ctx, gq.ctx, "All")
	if err := gq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Goal, *GoalQuery]()
	return withInterceptors[[]*Goal](ctx, gq, qr, gq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gq *GoalQuery) AllX(ctx context.Context) []*Goal {
	nodes, err := gq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Goal IDs.
func (gq *GoalQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if gq.ctx.Unique == nil && gq.path != nil {
		gq.Unique(true)
	}
	ctx = setContextOp(ctx, gq.ctx, "IDs")
	if err = gq.Select(goal.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gq *GoalQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := gq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gq *GoalQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gq.ctx, "Count")
	if err := gq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gq, querierCount[*GoalQuery](), gq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gq *GoalQuery) CountX(ctx context.Context) int {
	count, err := gq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gq *GoalQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gq.ctx, "Exist")
	switch _, err := gq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gq *GoalQuery) ExistX(ctx context.Context) bool {
	exist, err := gq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GoalQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gq *GoalQuery) Clone() *GoalQuery {
	if gq == nil {
		return nil
	}
	return &GoalQuery{
		config:          gq.config,
		ctx:             gq.ctx.Clone(),
		order:           append([]goal.OrderOption{}, gq.order...),
		inters:          append([]Interceptor{}, gq.inters...),
		predicates:      append([]predicate.Goal{}, gq.predicates...),
		withProfile:     gq.withProfile.Clone(),
		withCompetition: gq.withCompetition.Clone(),
		withSquad:       gq.withSquad.Clone(),
		// clone intermediate query.
		sql:  gq.sql.Clone(),
		path: gq.path,
	}
}

// WithProfile tells the query-builder to eager-load the nodes that are connected to
// the "profile" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GoalQuery) WithProfile(opts ...func(*ProfileQuery)) *GoalQuery {
	query := (&ProfileClient{config: gq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gq.withProfile = query
	return gq
}

// WithCompetition tells the query-builder to eager-load the nodes that are connected to
// the "competition" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GoalQuery) WithCompetition(opts ...func(*CompetitionQuery)) *GoalQuery {
	query := (&CompetitionClient{config: gq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gq.withCompetition = query
	return gq
}

// WithSquad tells the query-builder to eager-load the nodes that are connected to
// the "squad" edge. The optional arguments are used to configure the query builder of the edge.
func (gq *GoalQuery) WithSquad(opts ...func(*SquadQuery)) *GoalQuery {
	query := (&SquadClient{config: gq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gq.withSquad = query
	return gq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Goal.Query().
//		GroupBy(goal.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gq *GoalQuery) GroupBy(field string, fields ...string) *GoalGroupBy {
	gq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GoalGroupBy{build: gq}
	grbuild.flds = &gq.ctx.Fields
	grbuild.label = goal.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Goal.Query().
//		Select(goal.FieldCreatedAt).
//		Scan(ctx, &v)
func (gq *GoalQuery) Select(fields ...string) *GoalSelect {
	gq.ctx.Fields = append(gq.ctx.Fields, fields...)
	sbuild := &GoalSelect{GoalQuery: gq}
	sbuild.label = goal.Label
	sbuild.flds, sbuild.scan = &gq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GoalSelect configured with the given aggregations.
func (gq *GoalQuery) Aggregate(fns ...AggregateFunc) *GoalSelect {
	return gq.Select().Aggregate(fns...)
}

func (gq *GoalQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gq); err != nil {
				return err
			}
		}
	}
	for _, f := range gq.ctx.Fields {
		if !goal.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gq.path != nil {
		prev, err := gq.path(ctx)
		if err != nil {
			return err
		}
		gq.sql = prev
	}
	return nil
}

func (gq *GoalQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Goal, error) {
	var (
		nodes       = []*Goal{}
		withFKs     = gq.withFKs
		_spec       = gq.querySpec()
		loadedTypes = [3]bool{
			gq.withProfile != nil,
			gq.withCompetition != nil,
			gq.withSquad != nil,
		}
	)
	if gq.withProfile != nil || gq.withCompetition != nil || gq.withSquad != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, goal.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Goal).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Goal{config: gq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(gq.modifiers) > 0 {
		_spec.Modifiers = gq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gq.withProfile; query != nil {
		if err := gq.loadProfile(ctx, query, nodes, nil,
			func(n *Goal, e *Profile) { n.Edges.Profile = e }); err != nil {
			return nil, err
		}
	}
	if query := gq.withCompetition; query != nil {
		if err := gq.loadCompetition(ctx, query, nodes, nil,
			func(n *Goal, e *Competition) { n.Edges.Competition = e }); err != nil {
			return nil, err
		}
	}
	if query := gq.withSquad; query != nil {
		if err := gq.loadSquad(ctx, query, nodes, nil,
			func(n *Goal, e *Squad) { n.Edges.Squad = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gq *GoalQuery) loadProfile(ctx context.Context, query *ProfileQuery, nodes []*Goal, init func(*Goal), assign func(*Goal, *Profile)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Goal)
	for i := range nodes {
		if nodes[i].goal_profile == nil {
			continue
		}
		fk := *nodes[i].goal_profile
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(profile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "goal_profile" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gq *GoalQuery) loadCompetition(ctx context.Context, query *CompetitionQuery, nodes []*Goal, init func(*Goal), assign func(*Goal, *Competition)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Goal)
	for i := range nodes {
		if nodes[i].goal_competition == nil {
			continue
		}
		fk := *nodes[i].goal_competition
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(competition.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "goal_competition" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (gq *GoalQuery) loadSquad(ctx context.Context, query *SquadQuery, nodes []*Goal, init func(*Goal), assign func(*Goal, *Squad)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Goal)
	for i := range nodes {
		if nodes[i].goal_squad == nil {
			continue
		}
		fk := *nodes[i].goal_squad
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(squad.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "goal_squad" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gq *GoalQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gq.querySpec()
	if len(gq.modifiers) > 0 {
		_spec.Modifiers = gq.modifiers
	}
	_spec.Node.Columns = gq.ctx.Fields
	if len(gq.ctx.Fields) > 0 {
		_spec.Unique = gq.ctx.Unique != nil && *gq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gq.driver, _spec)
}

func (gq *GoalQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(goal.Table, goal.Columns, sqlgraph.NewFieldSpec(goal.FieldID, field.TypeUUID))
	_spec.From = gq.sql
	if unique := gq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gq.path != nil {
		_spec.Unique = true
	}
	if fields := gq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, goal.FieldID)
		for i := range fields {
			if fields[i] != goal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gq *GoalQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gq.driver.Dialect())
	t1 := builder.Table(goal.Table)
	columns := gq.ctx.Fields
	if len(columns) == 0 {
		columns = goal.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gq.sql != nil {
		selector = gq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gq.ctx.Unique != nil && *gq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range gq.modifiers {
		m(selector)
	}
	for _, p := range gq.predicates {
		p(selector)
	}
	for _, p := range gq.order {
		p(selector)
	}
	if offset := gq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gq *GoalQuery) Modify(modifiers ...func(s *sql.Selector)) *GoalSelect {
	gq.modifiers = append(gq.modifiers, modifiers...)
	return gq.Select()
}

// GoalGroupBy is the group-by builder for Goal entities.
type GoalGroupBy struct {
	selector
	build *GoalQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ggb *GoalGroupBy) Aggregate(fns ...AggregateFunc) *GoalGroupBy {
	ggb.fns = append(ggb.fns, fns...)
	return ggb
}

// Scan applies the selector query and scans the result into the given value.
func (ggb *GoalGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ggb.build.ctx, "GroupBy")
	if err := ggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalQuery, *GoalGroupBy](ctx, ggb.build, ggb, ggb.build.inters, v)
}

func (ggb *GoalGroupBy) sqlScan(ctx context.Context, root *GoalQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ggb.fns))
	for _, fn := range ggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ggb.flds)+len(ggb.fns))
		for _, f := range *ggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GoalSelect is the builder for selecting fields of Goal entities.
type GoalSelect struct {
	*GoalQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gs *GoalSelect) Aggregate(fns ...AggregateFunc) *GoalSelect {
	gs.fns = append(gs.fns, fns...)
	return gs
}

// Scan applies the selector query and scans the result into the given value.
func (gs *GoalSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gs.ctx, "Select")
	if err := gs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GoalQuery, *GoalSelect](ctx, gs.GoalQuery, gs, gs.inters, v)
}

func (gs *GoalSelect) sqlScan(ctx context.Context, root *GoalQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gs.fns))
	for _, fn := range gs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (gs *GoalSelect) Modify(modifiers ...func(s *sql.Selector)) *GoalSelect {
	gs.modifiers = append(gs.modifiers, modifiers...)
	return gs
}
