// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/notification"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/predicate"
	"github.com/jacobmaizel/swiftui-golang-app-demo/ent/profile"
	"github.com/jacobmaizel/swiftui-golang-app-demo/shared"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks     []Hook
	mutation  *NotificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nu *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetUpdatedAt sets the "updated_at" field.
func (nu *NotificationUpdate) SetUpdatedAt(t time.Time) *NotificationUpdate {
	nu.mutation.SetUpdatedAt(t)
	return nu
}

// SetTitle sets the "title" field.
func (nu *NotificationUpdate) SetTitle(s string) *NotificationUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetBody sets the "body" field.
func (nu *NotificationUpdate) SetBody(s string) *NotificationUpdate {
	nu.mutation.SetBody(s)
	return nu
}

// SetSent sets the "sent" field.
func (nu *NotificationUpdate) SetSent(t time.Time) *NotificationUpdate {
	nu.mutation.SetSent(t)
	return nu
}

// SetOpened sets the "opened" field.
func (nu *NotificationUpdate) SetOpened(t time.Time) *NotificationUpdate {
	nu.mutation.SetOpened(t)
	return nu
}

// SetNillableOpened sets the "opened" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableOpened(t *time.Time) *NotificationUpdate {
	if t != nil {
		nu.SetOpened(*t)
	}
	return nu
}

// ClearOpened clears the value of the "opened" field.
func (nu *NotificationUpdate) ClearOpened() *NotificationUpdate {
	nu.mutation.ClearOpened()
	return nu
}

// SetData sets the "data" field.
func (nu *NotificationUpdate) SetData(sd *shared.NotificationData) *NotificationUpdate {
	nu.mutation.SetData(sd)
	return nu
}

// ClearData clears the value of the "data" field.
func (nu *NotificationUpdate) ClearData() *NotificationUpdate {
	nu.mutation.ClearData()
	return nu
}

// SetProfileID sets the "profile" edge to the Profile entity by ID.
func (nu *NotificationUpdate) SetProfileID(id uuid.UUID) *NotificationUpdate {
	nu.mutation.SetProfileID(id)
	return nu
}

// SetProfile sets the "profile" edge to the Profile entity.
func (nu *NotificationUpdate) SetProfile(p *Profile) *NotificationUpdate {
	return nu.SetProfileID(p.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (nu *NotificationUpdate) Mutation() *NotificationMutation {
	return nu.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (nu *NotificationUpdate) ClearProfile() *NotificationUpdate {
	nu.mutation.ClearProfile()
	return nu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NotificationUpdate) Save(ctx context.Context) (int, error) {
	nu.defaults()
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotificationUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NotificationUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NotificationUpdate) check() error {
	if _, ok := nu.mutation.ProfileID(); nu.mutation.ProfileCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Notification.profile"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nu *NotificationUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationUpdate {
	nu.modifiers = append(nu.modifiers, modifiers...)
	return nu
}

func (nu *NotificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := nu.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if value, ok := nu.mutation.Sent(); ok {
		_spec.SetField(notification.FieldSent, field.TypeTime, value)
	}
	if value, ok := nu.mutation.Opened(); ok {
		_spec.SetField(notification.FieldOpened, field.TypeTime, value)
	}
	if nu.mutation.OpenedCleared() {
		_spec.ClearField(notification.FieldOpened, field.TypeTime)
	}
	if value, ok := nu.mutation.Data(); ok {
		_spec.SetField(notification.FieldData, field.TypeJSON, value)
	}
	if nu.mutation.DataCleared() {
		_spec.ClearField(notification.FieldData, field.TypeJSON)
	}
	if nu.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ProfileTable,
			Columns: []string{notification.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ProfileTable,
			Columns: []string{notification.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *NotificationMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (nuo *NotificationUpdateOne) SetUpdatedAt(t time.Time) *NotificationUpdateOne {
	nuo.mutation.SetUpdatedAt(t)
	return nuo
}

// SetTitle sets the "title" field.
func (nuo *NotificationUpdateOne) SetTitle(s string) *NotificationUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetBody sets the "body" field.
func (nuo *NotificationUpdateOne) SetBody(s string) *NotificationUpdateOne {
	nuo.mutation.SetBody(s)
	return nuo
}

// SetSent sets the "sent" field.
func (nuo *NotificationUpdateOne) SetSent(t time.Time) *NotificationUpdateOne {
	nuo.mutation.SetSent(t)
	return nuo
}

// SetOpened sets the "opened" field.
func (nuo *NotificationUpdateOne) SetOpened(t time.Time) *NotificationUpdateOne {
	nuo.mutation.SetOpened(t)
	return nuo
}

// SetNillableOpened sets the "opened" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableOpened(t *time.Time) *NotificationUpdateOne {
	if t != nil {
		nuo.SetOpened(*t)
	}
	return nuo
}

// ClearOpened clears the value of the "opened" field.
func (nuo *NotificationUpdateOne) ClearOpened() *NotificationUpdateOne {
	nuo.mutation.ClearOpened()
	return nuo
}

// SetData sets the "data" field.
func (nuo *NotificationUpdateOne) SetData(sd *shared.NotificationData) *NotificationUpdateOne {
	nuo.mutation.SetData(sd)
	return nuo
}

// ClearData clears the value of the "data" field.
func (nuo *NotificationUpdateOne) ClearData() *NotificationUpdateOne {
	nuo.mutation.ClearData()
	return nuo
}

// SetProfileID sets the "profile" edge to the Profile entity by ID.
func (nuo *NotificationUpdateOne) SetProfileID(id uuid.UUID) *NotificationUpdateOne {
	nuo.mutation.SetProfileID(id)
	return nuo
}

// SetProfile sets the "profile" edge to the Profile entity.
func (nuo *NotificationUpdateOne) SetProfile(p *Profile) *NotificationUpdateOne {
	return nuo.SetProfileID(p.ID)
}

// Mutation returns the NotificationMutation object of the builder.
func (nuo *NotificationUpdateOne) Mutation() *NotificationMutation {
	return nuo.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (nuo *NotificationUpdateOne) ClearProfile() *NotificationUpdateOne {
	nuo.mutation.ClearProfile()
	return nuo
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nuo *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notification entity.
func (nuo *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	nuo.defaults()
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NotificationUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok {
		v := notification.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NotificationUpdateOne) check() error {
	if _, ok := nuo.mutation.ProfileID(); nuo.mutation.ProfileCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Notification.profile"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (nuo *NotificationUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *NotificationUpdateOne {
	nuo.modifiers = append(nuo.modifiers, modifiers...)
	return nuo
}

func (nuo *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := nuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUUID))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := nuo.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := nuo.mutation.Body(); ok {
		_spec.SetField(notification.FieldBody, field.TypeString, value)
	}
	if value, ok := nuo.mutation.Sent(); ok {
		_spec.SetField(notification.FieldSent, field.TypeTime, value)
	}
	if value, ok := nuo.mutation.Opened(); ok {
		_spec.SetField(notification.FieldOpened, field.TypeTime, value)
	}
	if nuo.mutation.OpenedCleared() {
		_spec.ClearField(notification.FieldOpened, field.TypeTime)
	}
	if value, ok := nuo.mutation.Data(); ok {
		_spec.SetField(notification.FieldData, field.TypeJSON, value)
	}
	if nuo.mutation.DataCleared() {
		_spec.ClearField(notification.FieldData, field.TypeJSON)
	}
	if nuo.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ProfileTable,
			Columns: []string{notification.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notification.ProfileTable,
			Columns: []string{notification.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(nuo.modifiers...)
	_node = &Notification{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
